#!/bin/bash

echo "starting cleanup for $PWD"
curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/user/malware-file-b_clear | bash
curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/user/malware-hcess_clear | bash
curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/user/malware-db_options | bash
curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/user/malware-db_audit_clean | bash
curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/user/malware-cron_events | bash
echo "kindly verify user n remove what not"
curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/user/malware-db-user_list | bash
