#!/bin/bash

echo "Current Directory: $PWD"

# </dev/tty forces input from the terminal keyboard even when piped via curl
read -rp "Are you sure you want to clear for this directory? [y/n]: " confirm </dev/tty

# Convert input to lowercase to support 'y', 'Y', 'yes', or 'YES'
confirm_lc=$(echo "$confirm" | tr '[:upper:]' '[:lower:]')

if [[ "$confirm_lc" != "y" && "$confirm_lc" != "yes" ]]; then
    echo "Cleanup cancelled."
    exit 0
fi

echo "Starting cleanup for $PWD..."
curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/user/malware-file-b_clear | bash
curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/user/malware-hcess_clear | bash
curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/user/malware-db_options | bash
curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/user/malware-db_audit_clean | bash
curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/user/malware-cron_events_clear | bash
echo "kindly verify user n remove what not"
curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/user/malware-db-user_list | bash
