#!/bin/bash

current_dir="$PWD"

#this is whre the command selection starts

# Block execution if not inside a /home path or if running directly in /root
if [[ "$current_dir" == "/root" ]] || [[ "$current_dir" != /home* ]]; then
    echo "Cant run here this is not /home"
# Base home level (e.g., /home, /home1, /home2)
elif [[ "$current_dir" =~ ^/home[0-9]*$ ]]; then
    echo "Running home-level cleaner for: $current_dir"
    curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/malw-home | bash
else
    IFS='/' read -ra parts <<< "$current_dir"

    # User home level (e.g., /home/username)
    if [[ ${#parts[@]} -eq 3 ]]; then
        echo "Running user-level cleaner for user: ${parts[2]}"
        curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/malw-per-user | bash
    # Docroot level or deeper subdirectories (e.g., /home/username/public_html or deeper)
    elif [[ ${#parts[@]} -ge 4 ]]; then
        docroot="/${parts[1]}/${parts[2]}/${parts[3]}"
        echo "Running docroot cleaner (Target Docroot: $docroot)"
        curl -s https://raw.githubusercontent.com/HanifPaan/mware-clear/refs/heads/main/malw-droot | bash
    fi
fi
