#!/bin/bash

current_user=$(basename "$PWD")
pattern='helper_cf6e8521|SC_CORE_BOOT_VER|SCD1|retro-watcher-pad|agile-collector-hq|onyx-service-bit|flux-scanner-dex|\$_scp=dirname\(__FILE__\)\.'

echo "Cleaning malware files for user: $current_user..."
echo ""

grep -RalE \
  --exclude="*.txt" \
  --exclude="*.log" \
  --exclude="*.sql" \
  --exclude="*.svg" \
  --exclude="*.png" \
  --exclude="*.jpg" \
  --exclude="*.jpeg" \
  --exclude="*.gif" \
  --exclude="*.webp" \
  --exclude="*.ico" \
  --exclude="*.bmp" \
  --exclude="*.tiff" \
  --exclude="config-synced.php" \
  --exclude="scan_data.php" \
  --exclude="error_log" \
  --exclude-dir=".cagefs" \
  --exclude-dir="wflogs" \
  --exclude-dir=".cpanel" \
  --exclude-dir="tranziz" \
  --exclude-dir="aimeq" \
  --exclude-dir="mail" \
  --exclude-dir="*backups" \
  --exclude-dir=".cache" \
  --exclude-dir=".caldav" \
  "$pattern" . 2>/dev/null | xargs -r -I {} sh -c 'echo "Neutralizing: {}"; chattr -i "{}" 2>/dev/null; truncate -s 0 "{}"; chown nobody:nobody "{}"; chattr +i "{}"'

echo ""
echo "files above cleaned up completed"
